import Header from '../components/Header'
import '../styles/globals.css'
import Head from 'next/head'
import { CounterProvider } from '../context/Tool'

function MyApp({ Component, pageProps }) {
  return (
    <>
    <Head>
        <title>Tinkerer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header/>

    <CounterProvider>
    <Component {...pageProps} />
    </CounterProvider>
    
    </>
  )
}

export default MyApp
