import { useState } from "react"
import Head from 'next/head'
import Weapon from '../components/Weapon'
import { useCount } from '../context/Tool'

export default function Home() {
  const [query, setQuery] = useState('')
  const count = useCount()
  return (
    <div>
      <Head>
        <title>Tinkerer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="space-x-2">Your weapon of Choice?</h1>
        <form className="flex sm:flex-row items-center h-auto ml-4">
                  <input value={query} type="text" placeholder="Search" className="text-white bg-gray-800 shadow-lg w-screen h-10 " required onChange={event=>setQuery(event.target.value)}/>
                  <button type="submit" className="bg-gray-700 w-20 h-10 m-5" onClick={(e) => {reset(e);}}>Reset</button>
        </form>
      </div>
      <Weapon query={query}/>
    </div>
  )
}
