import Head from 'next/head'
import Header from '../components/Header'
import Results from '../components/Results'
import Search from '../components/Search';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tinkerer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Search/>
    </div>
  )
}
